name: pre-commit
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: '>=1.20.0'
      - name: Install goimports
        run: go install golang.org/x/tools/cmd/goimports@latest
      - uses: actions/checkout@v3
      - name: pre-commit
        uses: pre-commit/action@v3.0.0
